version: '3.8'
services:
  nft_platform:
    container_name: nft_platform
    image: postgres:14.2
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'